### PR TITLE
super tiny improvement to maven pom changes

### PR DESCRIPTION
**Pull request by alph486**

### CODE REVIEW

**Comment by Vladislav-Zolotaryov** [comment]
Really?

**Comment by alph486** [comment]
Easy...Just for copy paste man, you don't have to merge it.

**Comment by fernandezpablo85** [comment]
This would assume that scribe is your only dependency (and that's hardly the common case).

**Comment by alph486** [comment]
Yes context was bad after looking sorry; I would have done something differently but clearly it's a bit too tedious. Thanks for looking.

**Comment by fernandezpablo85** [comment]
no problem man, thanks for trying to improve scribe :)

**Pull request closed without merging**
