### PR TITLE
LinkedIn OAuth 2.0 implementation

### PR DESCRIPTION
**Pull request by Vladislav-Zolotaryov**
LinkedIn OAuth 2.0 implementation
Addition of state field for CSRF protection (known to work with LinkedIn)
Example how to use LinkedIn OAuth 2.0

### CODE REVIEW

**Comment by simtse** [comment]
@fernandezpablo85 Could you have a look at this pull request and see if it can make it into the next release soon?

**Comment by fernandezpablo85** [comment]
Oauth 2.0 support is discontinued.

**Comment by xberger** [comment]
When I encountered the missing state verification I was puzzled to find the statement "Oauth 2.0 support is discontinued" buried just here, but not visible on the main readme, let alone in the example or service classes.
I would propose to clearly state the discontinuation on the main readme so that people can notice on time that important features are missing. Does that makes sense?

**Comment by kullfar** [comment]
Why do you think OAuth2 LinkedIn is discontinued in ScribeJava?

This Pull Request and comments here are just history. Actual information is in the main readme and in the examples
https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/LinkedIn20Example.java

**Pull request closed without merging**
